### ISSUE TITLE
Invite your friends!

### ISSUE THREAD

**Issue by Maslor** [Maslor/code-school#1]

**Comment by Maslor** [comment]
Diogo, ensina aí os teus colegas @Patcholito

**Comment by Maslor** [comment]
@Patcholito

**Comment by Patcholito** [comment]
N tenho amigos ;(

**Comment by Maslor** [comment]
De certeza que aqueles teus colegas interessados em programação querem experimentar. @Patcholito

**Comment by Patcholito** [comment]
nah, não querem, eles são uns desinteressados :horse:

**Comment by Patcholito** [comment]
eles estão todos offline e o meu telemóvel está sem bateria desde ontem.... :battery:

**Comment by Patcholito** [comment]
ja agora quando é q vais fazer trabalhos manuais no raspberry?

**Comment by Maslor** [comment]
Eu não tenho tido tempo para o raspberry, a ver se trato disso mal consiga. Estou a produzir um novo enunciado... Ainda é mais fácil diria eu. No entanto tem mais aplicação no mundo real. @Patcholito

**Comment by Patcholito** [comment]
Para que é que serve a app?

**Comment by Maslor** [comment]
Qual é o mail do bruno? @Patcholito

**Comment by Maslor** [comment]
Já agora, corrigi os teus comments que não se percebia em que língua estavam escritos @Patcholito
